OrdererOrgs:
  - Name: Orderer-Member1
    Domain: member1.example.com
    Specs:
      - Hostname: orderer0
PeerOrgs:
  - Name: Peer-Member1
    Domain: member1.example.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Peer-Member2
    Domain: member2.example.com
    Template:
      Count: 1
    Users:
      Count: 1
